=== drdhaval2785/inriaxmlwrapper/SL_morph.dtd
<!-- DTD for Sanskrit morphology              Author Gerard.Huet@inria.fr -->
<!-- Free format for XML linguistic data interchange, no copyright        -->

<!-- Version history   
     Version 0.1 Date: Aug 15 2003 
     Version 1.1 Date: Dec 05 2005
     Version 1.2 Date: Aug 21 2006 
     Version 1.3 Date: Feb 19 2008 
     Version 1.4 Date: Jul 23 2008 - indeclinable forms more informative
     Version 1.5 Date: Aug 16 2008 - conditional added
     Version 1.6 Date: Dec 26 2008 - injunctive added
     Version 1.7 Date: Fev 26 2009 - benedictive added
     Version 2.1 Date: Dec 16 2010 - ga.na added, parameterized for SL 
     Version 2.2 Date: Dec 18 2010 - validated data in SL transliteration
     Version 2.3 Date: Dec 20 2010 - renamed SL_skt_morph.dtd
     Version 2.4 Date: Jun 05 2012 - added tag avya for avyayiibhaava ifc
     Version 2.5 Date: Nov 05 2012 - perif future has voice, gana optional attr
     Version 3.1 Date: Nov 22 2013 - proper kridanta structure for participles
     Version 3.2 Date: Dec 23 2014 - fix gn attribute of prs consistent with DTD
     Version 3.3 Date: Jun 08 2015 - tasil indeclinable taddhitas added
-->

<!-- Transliteration of forms according to Sanskrit Library scheme SL1:
a A i I u U f F x e E o O M ~ H
k K g G N c C j J Y w W q Q R t T d D n p P b B m y r l v S z s h
The generating stem is a form optionally suffixed by a homonymy index #n,
it indexes an entry in the Sanskrit Heritage dictionary.
-->

<!ELEMENT forms (f | pv)*> <!-- list of all inflected forms -->

<!ELEMENT f ((iic | iiv | uf | na | v | pa | ab | iip | vu | avya)*,s)> <!-- inflected form entry -->
<!ATTLIST f form CDATA #REQUIRED>

<!ELEMENT s EMPTY>  <!-- lexicon stem or root generating the form -->
<!ATTLIST s stem CDATA #REQUIRED>

<!ELEMENT pv EMPTY> <!-- preverb sequence -->
<!ATTLIST pv form CDATA #REQUIRED>

<!-- gender -->
<!ELEMENT mas EMPTY> <!-- masculine -->
<!ELEMENT neu EMPTY> <!-- neuter -->
<!ELEMENT fem EMPTY> <!-- feminine -->
<!ELEMENT dei EMPTY> <!-- deictic or numeral -->

<!-- number -->
<!ELEMENT sg EMPTY> <!-- singular -->
<!ELEMENT du EMPTY> <!-- dual -->
<!ELEMENT pl EMPTY> <!-- plural -->

<!-- person -->
<!ELEMENT fst EMPTY> <!-- 1 -->
<!ELEMENT snd EMPTY> <!-- 2 -->
<!ELEMENT trd EMPTY> <!-- 3 -->

<!-- case -->
<!ELEMENT nom EMPTY>
<!ELEMENT voc EMPTY>
<!ELEMENT acc EMPTY>
<!ELEMENT ins EMPTY>
<!ELEMENT dat EMPTY>
<!ELEMENT abl EMPTY>
<!ELEMENT gen EMPTY>
<!ELEMENT loc EMPTY>

<!ELEMENT iic EMPTY> <!-- beginning of compound -->
<!ELEMENT iiv EMPTY> <!-- before auxiliary verb -->
<!ELEMENT iip (cj,no)>  <!-- beginning of compound from participle -->
<!ELEMENT uf (ind | interj | parti | prep | conj | tasil)>   <!-- indeclinable form -->
<!ELEMENT ind EMPTY> <!-- indeclinable - adverb -->
<!ELEMENT avya EMPTY> <!-- right component of avyayiibhaava -->
<!ELEMENT interj EMPTY> <!-- indeclinable - interjection -->
<!ELEMENT parti EMPTY> <!-- indeclinable - particle -->
<!ELEMENT prep EMPTY> <!-- indeclinable - preposition -->
<!ELEMENT conj EMPTY> <!-- indeclinable - conjunction -->
<!ELEMENT tasil EMPTY> <!-- indeclinable - adverbs of manner in -tas -->
<!ELEMENT pa (na,kr)> <!-- participial forms have nominal declension parameters and kridanta generator -->
<!ELEMENT kr (vb)>     <!-- kridanta generator has verbal structure -->
<!ELEMENT ab (cj)>     <!-- abs in tvaa with conjugation -->
<!ELEMENT vb (cj,no)>   <!-- verbal has conjugation and nominal -->
<!ELEMENT vu (cj,iv)>   <!-- indeclinable verbal form -->
<!ELEMENT na ((nom | voc | acc | ins | dat | abl | gen | loc), 
              (sg | du | pl), 
              (mas | neu | fem | dei))> <!-- noun/adjective with case, number, gender -->
<!ELEMENT np ((sg | du | pl),   
              (fst | snd | trd))>  <!-- number, person -->

<!ELEMENT v (cj,sys,np)>  <!-- finite root form has conjugation, system, number and person -->

<!ELEMENT cj (prim | ca | int | des)> <!-- conjugation primary or secondary -->
<!ELEMENT prim EMPTY> <!-- primary -->
<!ELEMENT ca EMPTY>   <!-- causative -->
<!ELEMENT int EMPTY>  <!-- intensive -->
<!ELEMENT des EMPTY>  <!-- desiderative -->

<!ELEMENT sys (prs | pas | tp | pef)> <!-- system is present system, passive system, tense paradigm or periphratic perfect -->

<!ELEMENT prs (md, (para | atma))> <!-- mode and pade -->
<!ATTLIST prs gn CDATA #IMPLIED> <!-- present system has opt gana attribute -->

<!ELEMENT gn (#PCDATA)> <!-- gana is integer between 1 and 11 (denominatives) -->

<!ELEMENT md (pr | ip | op | im)> <!-- mode is present, imperative, optative or imperfect -->
<!ELEMENT pr EMPTY> <!-- present -->
<!ELEMENT ip EMPTY> <!-- imperative -->
<!ELEMENT op EMPTY> <!-- optative -->
<!ELEMENT im EMPTY> <!-- imperfect -->

<!ELEMENT para EMPTY> <!-- parasmaipade -->
<!ELEMENT atma EMPTY> <!-- atmanepade -->
<!ELEMENT pass EMPTY> <!-- passive voice -->

<!ELEMENT pas (md)> <!-- passive system has mode-->

<!ELEMENT tp ((fut | prf | aor | inj | cnd | ben),(para | atma | pass))> <!-- tense paradigm has tense and voice -->

<!ELEMENT fut EMPTY> <!-- future -->
<!ELEMENT prf EMPTY> <!-- perfect -->
<!ELEMENT aor (#PCDATA)> <!-- aorist has kind, integer between 1 and 7-->
<!ELEMENT inj (#PCDATA)> <!-- injunctive (aorist without augment) had kind -->
<!ELEMENT cnd EMPTY> <!-- conditional -->
<!ELEMENT ben EMPTY> <!-- benedictive -->

<!ELEMENT pef (para | atma)> <!-- perif future -->
<!ELEMENT no (ppp | ppa | ppr | pprp | ppft | pfut | pfutp)> <!-- nominal form is one among kridanta formation schemes -->
<!ELEMENT ppp EMPTY> <!-- passive past participle -->
<!ELEMENT ppa EMPTY> <!-- active past participle -->
<!ELEMENT ppr (para | atma)>  <!-- present participle has pade  -->
<!ATTLIST ppr gn CDATA #IMPLIED> <!-- present system has opt gana attribute -->
<!ELEMENT pprp EMPTY>     <!-- passive present participle -->
<!ELEMENT ppft (para | atma)> <!-- perfect participle has pade -->
<!ELEMENT pfut (para | atma)> <!-- future participle has pade -->
<!ELEMENT pfutp (gya | iya | tav)>    <!-- passive future participle has geruntive formation scheme -->

<!ELEMENT gya EMPTY> <!-- gerundive in ya -->
<!ELEMENT iya EMPTY> <!-- gerundive in Iya -->
<!ELEMENT tav EMPTY> <!-- gerundive in tavya -->

<!ELEMENT iv (inf | abs | per)> <!-- invariable verbal form -->
<!ELEMENT inf EMPTY> <!-- infinitive -->
<!ELEMENT abs EMPTY> <!-- absolutive in ya -->
<!ELEMENT per EMPTY> <!-- periphrastic perfect -->

<!-- English and Devanagari equivalents -->
<!-- present - law, imperfect - laN, optative - viDiliN, imperative - low, future - lfw, conditional - lfN, periphrastic future - luw, perfect - liw, aorist - luN, injunctive - AgamABAvayuktaluN, benedictive - ASIrliN -->

=== drdhaval2785/inriaxmlwrapper/SL_pronouns.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE forms SYSTEM "SL_morph.dtd">
<!-- header
<meta name="title" content="Sanskrit Morphology"; ps ">
<meta name="author" content="
G&#233;rard Huet"><meta name="date" content="
22 Juillet 2015"><meta name="copyright" content="
&#169; G&#233;rard Huet 1994-2015"><meta name="keywords" content="sanskrit; morphology"> -->
<forms>
<f form="adas"><na><acc/><sg/><neu/></na><na><nom/><sg/><neu/></na><s stem="adas"/></f>
<f form="aDarayA"><na><ins/><sg/><fem/></na><s stem="aDara"/></f>
<f form="aDarayos"><na><loc/><du/><fem/></na><na><gen/><du/><fem/></na><s stem="aDara"/></f>
<f form="aDarasyAm"><na><loc/><sg/><fem/></na><s stem="aDara"/></f>
<f form="aDarasyAs"><na><gen/><sg/><fem/></na><na><abl/><sg/><fem/></na><s stem="aDara"/></f>
<f form="aDarasyE"><na><dat/><sg/><fem/></na><s stem="aDara"/></f>
<f form="aDarA"><na><nom/><sg/><fem/></na><s stem="aDara"/></f>
<f form="aDarABis"><na><ins/><pl/><fem/></na><s stem="aDara"/></f>
<f form="aDarAByas"><na><abl/><pl/><fem/></na><na><dat/><pl/><fem/></na><s stem="aDara"/></f>
<f form="aDarAByAm"><na><abl/><du/><fem/></na><na><dat/><du/><fem/></na><na><ins/><du/><fem/></na><s stem="aDara"/></f>
<f form="aDarAm"><na><acc/><sg/><fem/></na><s stem="aDara"/></f>
<f form="aDarAs"><na><acc/><pl/><fem/></na><na><nom/><pl/><fem/></na><s stem="aDara"/></f>
<f form="aDarAsAm"><na><gen/><pl/><fem/></na><s stem="aDara"/></f>
<f form="aDarAsu"><na><loc/><pl/><fem/></na><s stem="aDara"/></f>
<f form="aDare"><na><acc/><du/><fem/></na><na><nom/><du/><fem/></na><s stem="aDara"/></f>
<f form="anayA"><na><ins/><sg/><fem/></na><s stem="ayam"/></f>
<f form="anayos"><na><loc/><du/><mas/></na><na><gen/><du/><mas/></na><na><loc/><du/><fem/></na><na><gen/><du/><fem/></na><na><loc/><du/><neu/></na><na><gen/><du/><neu/></na><s stem="ayam"/></f>
<f form="anekayA"><na><ins/><sg/><fem/></na><s stem="aneka"/></f>
<f form="anekayos"><na><loc/><du/><fem/></na><na><gen/><du/><fem/></na><s stem="aneka"/></f>
<f form="anekasyAm"><na><loc/><sg/><fem/></na><s stem="aneka"/></f>
<f form="anekasyAs"><na><gen/><sg/><fem/></na><na><abl/><sg/><fem/></na><s stem="aneka"/></f>
<f form="anekasyE"><na><dat/><sg/><fem/></na><s stem="aneka"/></f>
<f form="anekA"><na><nom/><sg/><fem/></na><s stem="aneka"/></f>
<f form="anekABis"><na><ins/><pl/><fem/></na><s stem="aneka"/></f>
<f form="anekAByas"><na><abl/><pl/><fem/></na><na><dat/><pl/><fem/></na><s stem="aneka"/></f>
<f form="anekAByAm"><na><abl/><du/><fem/></na><na><dat/><du/><fem/></na><na><ins/><du/><fem/></na><s stem="aneka"/></f>
<f form="anekAm"><na><acc/><sg/><fem/></na><s stem="aneka"/></f>
<f form="anekAs"><na><acc/><pl/><fem/></na><na><nom/><pl/><fem/></na><s stem="aneka"/></f>
<f form="anekAsAm"><na><gen/><pl/><fem/></na><s stem="aneka"/></f>
<f form="anekAsu"><na><loc/><pl/><fem/></na><s stem="aneka"/></f>
<f form="aneke"><na><acc/><du/><fem/></na><na><nom/><du/><fem/></na><s stem="aneka"/></f>
<f form="anena"><na><ins/><sg/><mas/></na><na><ins/><sg/><neu/></na><s stem="ayam"/></f>
<f form="antarayA"><na><ins/><sg/><fem/></na><s stem="antara"/></f>
<f form="antarayos"><na><loc/><du/><fem/></na><na><gen/><du/><fem/></na><s stem="antara"/></f>
<f form="antarasyAm"><na><loc/><sg/><fem/></na><s stem="antara"/></f>
<f form="antarasyAs"><na><gen/><sg/><fem/></na><na><abl/><sg/><fem/></na><s stem="antara"/></f>
<f form="antarasyE"><na><dat/><sg/><fem/></na><s stem="antara"/></f>
<f form="antarA"><na><nom/><sg/><fem/></na><s stem="antara"/></f>
<f form="antarABis"><na><ins/><pl/><fem/></na><s stem="antara"/></f>
<f form="antarAByas"><na><abl/><pl/><fem/></na><na><dat/><pl/><fem/></na><s stem="antara"/></f>
<f form="antarAByAm"><na><abl/><du/><fem/></na><na><dat/><du/><fem/></na><na><ins/><du/><fem/></na><s stem="antara"/></f>
<f form="antarAm"><na><acc/><sg/><fem/></na><s stem="antara"/></f>
<f form="antarAs"><na><acc/><pl/><fem/></na><na><nom/><pl/><fem/></na><s stem="antara"/></f>
<f form="antarAsAm"><na><gen/><pl/><fem/></na><s stem="antara"/></f>
<f form="antarAsu"><na><loc/><pl/><fem/></na><s stem="antara"/></f>
<f form="antare"><na><acc/><du/><fem/></na><na><nom/><du/><fem/></na><s stem="antara"/></f>
<f form="anyat"><na><acc/><sg/><neu/></na><na><nom/><sg/><neu/></na><s stem="anya"/></f>
<f form="anyam"><na><acc/><sg/><mas/></na><s stem="anya"/></f>
<f form="anyayA"><na><ins/><sg/><fem/></na><s stem="anya"/></f>
<f form="anyayos"><na><loc/><du/><mas/></na><na><gen/><du/><mas/></na><na><loc/><du/><fem/></na><na><gen/><du/><fem/></na><na><loc/><du/><neu/></na><na><gen/><du/><neu/></na><s stem="anya"/></f>
<f form="anyas"><na><nom/><sg/><mas/></na><s stem="anya"/></f>
<f form="anyasmAt"><na><abl/><sg/><mas/></na><na><abl/><sg/><neu/></na><s stem="anya"/></f>
<f form="anyasmin"><na><loc/><sg/><mas/></na><na><loc/><sg/><neu/></na><s stem="anya"/></f>
<f form="anyasmE"><na><dat/><sg/><mas/></na><na><dat/><sg/><neu/></na><s stem="anya"/></f>
<f form="anyasya"><na><gen/><sg/><mas/></na><na><gen/><sg/><neu/></na><s stem="anya"/></f>
<f form="anyasyAm"><na><loc/><sg/><fem/></na><s stem="anya"/></f>
<f form="anyasyAs"><na><gen/><sg/><fem/></na><na><abl/><sg/><fem/></na><s stem="anya"/></f>
<f form="anyasyE"><na><dat/><sg/><fem/></na><s stem="anya"/></f>
<f form="anyA"><na><nom/><sg/><fem/></na><s stem="anya"/></f>
<f form="anyAn"><na><acc/><pl/><mas/></na><s stem="anya"/></f>
<f form="anyAni"><na><acc/><pl/><neu/></na><na><nom/><pl/><neu/></na><s stem="anya"/></f>
<f form="anyABis"><na><ins/><pl/><fem/></na><s stem="anya"/></f>
<f form="anyAByas"><na><abl/><pl/><fem/></na><na><dat/><pl/><fem/></na><s stem="anya"/></f>
<f form="anyAByAm"><na><abl/><du/><mas/></na><na><dat/><du/><mas/></na><na><ins/><du/><mas/></na><na><abl/><du/><fem/></na><na><dat/><du/><fem/></na><na><ins/><du/><fem/></na><na><abl/><du/><neu/></na><na><dat/><du/><neu/></na><na><ins/><du/><neu/></na><s stem="anya"/></f>
<f form="anyAm"><na><acc/><sg/><fem/></na><s stem="anya"/></f>
<f form="anyAs"><na><acc/><pl/><fem/></na><na><nom/><pl/><fem/></na><s stem="anya"/></f>
<f form="anyAsAm"><na><gen/><pl/><fem/></na><s stem="anya"/></f>
<f form="anyAsu"><na><loc/><pl/><fem/></na><s stem="anya"/></f>
<f form="anye"><na><nom/><pl/><mas/></na><na><acc/><du/><fem/></na><na><nom/><du/><fem/></na><na><acc/><du/><neu/></na><na><nom/><du/><neu/></na><s stem="anya"/></f>
<f form="anyena"><na><ins/><sg/><mas/></na><na><ins/><sg/><neu/></na><s stem="anya"/></f>
<f form="anyeByas"><na><abl/><pl/><mas/></na><na><dat/><pl/><mas/></na><na><abl/><pl/><neu/></na><na><dat/><pl/><neu/></na><s stem="anya"/></f>
<f form="anyezAm"><na><gen/><pl/><mas/></na><na><gen/><pl/><neu/></na><s stem="anya"/></f>
<f form="anyezu"><na><loc/><pl/><mas/></na><na><loc/><pl/><neu/></na><s stem="anya"/></f>
<f form="anyEs"><na><ins/><pl/><mas/></na><na><ins/><pl/><neu/></na><s stem="anya"/></f>
<f form="anyO"><na><acc/><du/><mas/></na><na><nom/><du/><mas/></na><s stem="anya"/></f>
<f form="aparayA"><na><ins/><sg/><fem/></na><s stem="apara"/></f>
<f form="aparayos"><na><loc/><du/><fem/></na><na><gen/><du/><fem/></na><s stem="apara"/></f>
<f form="aparasyAm"><na><loc/><sg/><fem/></na><s stem="apara"/></f>
<f form="aparasyAs"><na><gen/><sg/><fem/></na><na><abl/><sg/><fem/></na><s stem="apara"/></f>
<f form="aparasyE"><na><dat/><sg/><fem/></na><s stem="apara"/></f>
<f form="aparA"><na><nom/><sg/><fem/></na><s stem="apara"/></f>
<f form="aparABis"><na><ins/><pl/><fem/></na><s stem="apara"/></f>
<f form="aparAByas"><na><abl/><pl/><fem/></na><na><dat/><pl/><fem/></na><s stem="apara"/></f>
<f form="aparAByAm"><na><abl/><du/><fem/></na><na><dat/><du/><fem/></na><na><ins/><du/><fem/></na><s stem="apara"/></f>
<f form="aparAm"><na><acc/><sg/><fem/></na><s stem="apara"/></f>
<f form="aparAs"><na><acc/><pl/><fem/></na><na><nom/><pl/><fem/></na><s stem="apara"/></f>
<f form="aparAsAm"><na><gen/><pl/><fem/></na><s stem="apara"/></f>
<f form="aparAsu"><na><loc/><pl/><fem/></na><s stem="apara"/></f>
<f form="apare"><na><acc/><du/><fem/></na><na><nom/><du/><fem/></na><s stem="apara"/></f>
<f form="amI"><na><nom/><pl/><mas/></na><s stem="adas"/></f>
<f form="amIBis"><na><ins/><pl/><neu/></na><na><ins/><pl/><mas/></na><s stem="adas"/></f>
<f form="amIByas"><na><abl/><pl/><neu/></na><na><dat/><pl/><neu/></na><na><abl/><pl/><mas/></na><na><dat/><pl/><mas/></na><s stem="adas"/></f>
<f form="amIzAm"><na><gen/><pl/><neu/></na><na><gen/><pl/><mas/></na><s stem="adas"/></f>
<f form="amIzu"><na><loc/><pl/><neu/></na><na><loc/><pl/><mas/></na><s stem="adas"/></f>
<f form="amunA"><na><ins/><sg/><neu/></na><na><ins/><sg/><mas/></na><s stem="adas"/></f>
<f form="amum"><na><acc/><sg/><mas/></na><s stem="adas"/></f>
<f form="amuyA"><na><ins/><sg/><fem/></na><s stem="adas"/></f>
<f form="amuyos"><na><loc/><du/><neu/></na><na><gen/><du/><neu/></na><na><loc/><du/><mas/></na><na><gen/><du/><mas/></na><na><loc/><du/><fem/></na><na><gen/><du/><fem/></na><s stem="adas"/></f>
<f form="amuzmAt"><na><abl/><sg/><neu/></na><na><abl/><sg/><mas/></na><s stem="adas"/></f>
<f form="amuzmin"><na><loc/><sg/><neu/></na><na><loc/><sg/><mas/></na><s stem="adas"/></f>
<f form="amuzmE"><na><dat/><sg/><neu/></na><na><dat/><sg/><mas/></na><s stem="adas"/></f>
<f form="amuzya"><na><gen/><sg/><neu/></na><na><gen/><sg/><mas/></na><s stem="adas"/></f>
<f form="amuzyAm"><na><loc/><sg/><fem/></na><s stem="adas"/></f>
<f form="amuzyAs"><na><gen/><sg/><fem/></na><na><abl/><sg/><fem/></na><s stem="adas"/></f>
<f form="amuzyE"><na><dat/><sg/><fem/></na><s stem="adas"/></f>
<f form="amU"><na><acc/><du/><neu/></na><na><nom/><du/><neu/></na><na><acc/><du/><mas/></na><na><nom/><du/><mas/></na><na><acc/><du/><fem/></na><na><nom/><du/><fem/></na><s stem="adas"/></f>
<f form="amUn"><na><acc/><pl/><mas/></na><s stem="adas"/></f>
<f form="amUni"><na><acc/><pl/><neu/></na><na><nom/><pl/><neu/></na><s stem="adas"/></f>
<f form="amUBis"><na><ins/><pl/><fem/></na><s stem="adas"/></f>
<f form="amUByas"><na><abl/><pl/><fem/></na><na><dat/><pl/><fem/></na><s stem="adas"/></f>
